#!/bin/bash

# Script to download tech icons from CDN to local directory
# This eliminates the jsDelivr service worker deprecation warning

ICONS_DIR="public/icons/tech"

# Create directory if it doesn't exist
mkdir -p "$ICONS_DIR"

# Download icons from jsdelivr
curl -s -o "$ICONS_DIR/nextjs.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"
curl -s -o "$ICONS_DIR/react.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
curl -s -o "$ICONS_DIR/vuejs.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg"
curl -s -o "$ICONS_DIR/angular.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg"
curl -s -o "$ICONS_DIR/typescript.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
curl -s -o "$ICONS_DIR/nodejs.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"
curl -s -o "$ICONS_DIR/python.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
curl -s -o "$ICONS_DIR/java.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
curl -s -o "$ICONS_DIR/dotnetcore.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg"
curl -s -o "$ICONS_DIR/php.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg"
curl -s -o "$ICONS_DIR/flutter.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg"
curl -s -o "$ICONS_DIR/swift.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg"
curl -s -o "$ICONS_DIR/kotlin.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg"
curl -s -o "$ICONS_DIR/aws.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
curl -s -o "$ICONS_DIR/azure.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg"
curl -s -o "$ICONS_DIR/googlecloud.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg"
curl -s -o "$ICONS_DIR/docker.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"
curl -s -o "$ICONS_DIR/kubernetes.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg"
curl -s -o "$ICONS_DIR/tensorflow.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg"
curl -s -o "$ICONS_DIR/postgresql.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
curl -s -o "$ICONS_DIR/mongodb.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
curl -s -o "$ICONS_DIR/cypress.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cypressio/cypressio-original.svg"
curl -s -o "$ICONS_DIR/selenium.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg"
curl -s -o "$ICONS_DIR/tailwindcss.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg"
curl -s -o "$ICONS_DIR/wordpress.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg"
curl -s -o "$ICONS_DIR/firebase.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg"
curl -s -o "$ICONS_DIR/android.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg"
curl -s -o "$ICONS_DIR/apple.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apple/apple-original.svg"
curl -s -o "$ICONS_DIR/openai.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg"
curl -s -o "$ICONS_DIR/stripe.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/stripe/stripe-original.svg"
curl -s -o "$ICONS_DIR/paypal.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/paypal/paypal-original.svg"
curl -s -o "$ICONS_DIR/woocommerce.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/woocommerce/woocommerce-original.svg"
curl -s -o "$ICONS_DIR/shopify.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/shopify/shopify-original.svg"
curl -s -o "$ICONS_DIR/magento.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/magento/magento-original.svg"
curl -s -o "$ICONS_DIR/prestashop.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prestashop/prestashop-original.svg"
curl -s -o "$ICONS_DIR/mysql.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"
curl -s -o "$ICONS_DIR/redis.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg"
curl -s -o "$ICONS_DIR/elasticsearch.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg"
curl -s -o "$ICONS_DIR/oracle.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg"
curl -s -o "$ICONS_DIR/mssql.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg"
curl -s -o "$ICONS_DIR/dynamodb.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dynamodb/dynamodb-original.svg"
curl -s -o "$ICONS_DIR/cassandra.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachecassandra/apachecassandra-original.svg"
curl -s -o "$ICONS_DIR/salesforce.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/salesforce/salesforce-original.svg"
curl -s -o "$ICONS_DIR/jira.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg"
curl -s -o "$ICONS_DIR/slack.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slack/slack-original.svg"
curl -s -o "$ICONS_DIR/figma.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg"
curl -s -o "$ICONS_DIR/terraform.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg"
curl -s -o "$ICONS_DIR/ansible.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg"
curl -s -o "$ICONS_DIR/jenkins.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg"
curl -s -o "$ICONS_DIR/gitlab.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg"
curl -s -o "$ICONS_DIR/circleci.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/circleci/circleci-plain.svg"
curl -s -o "$ICONS_DIR/datadog.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/datadog/datadog-original.svg"
curl -s -o "$ICONS_DIR/prometheus.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg"
curl -s -o "$ICONS_DIR/grafana.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg"
curl -s -o "$ICONS_DIR/go.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original-wordmark.svg"
curl -s -o "$ICONS_DIR/rust.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg"
curl -s -o "$ICONS_DIR/scala.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scala/scala-original.svg"
curl -s -o "$ICONS_DIR/ruby.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg"
curl -s -o "$ICONS_DIR/svelte.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg"
curl -s -o "$ICONS_DIR/nuxtjs.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg"
curl -s -o "$ICONS_DIR/pandas.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg"
curl -s -o "$ICONS_DIR/spark.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachespark/apachespark-original.svg"
curl -s -o "$ICONS_DIR/hadoop.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/hadoop/hadoop-original.svg"
curl -s -o "$ICONS_DIR/kafka.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg"
curl -s -o "$ICONS_DIR/linux.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg"
curl -s -o "$ICONS_DIR/nginx.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg"
curl -s -o "$ICONS_DIR/git.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
curl -s -o "$ICONS_DIR/spring.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg"
curl -s -o "$ICONS_DIR/django.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg"
curl -s -o "$ICONS_DIR/fastapi.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg"
curl -s -o "$ICONS_DIR/laravel.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg"
curl -s -o "$ICONS_DIR/symfony.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/symfony/symfony-original.svg"
curl -s -o "$ICONS_DIR/vercel.svg" "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg"

# Download icons from other CDNs
curl -s -o "$ICONS_DIR/powerbi.svg" "https://upload.wikimedia.org/wikipedia/commons/c/cf/New_Power_BI_Logo.svg"
curl -s -o "$ICONS_DIR/framer.svg" "https://www.vectorlogo.zone/logos/framer/framer-icon.svg"
curl -s -o "$ICONS_DIR/expo.svg" "https://www.vectorlogo.zone/logos/expoio/expoio-icon.svg"
curl -s -o "$ICONS_DIR/midjourney.svg" "https://www.vectorlogo.zone/logos/midjourney/midjourney-icon.svg"
curl -s -o "$ICONS_DIR/zapier.svg" "https://www.vectorlogo.zone/logos/zapier/zapier-icon.svg"
curl -s -o "$ICONS_DIR/github.svg" "https://www.vectorlogo.zone/logos/github/github-icon.svg"
curl -s -o "$ICONS_DIR/google-analytics.svg" "https://www.vectorlogo.zone/logos/google_analytics/google_analytics-icon.svg"
curl -s -o "$ICONS_DIR/sap.svg" "https://www.vectorlogo.zone/logos/sap/sap-icon.svg"
curl -s -o "$ICONS_DIR/snowflake.svg" "https://www.vectorlogo.zone/logos/snowflake/snowflake-icon.svg"
curl -s -o "$ICONS_DIR/databricks.svg" "https://www.vectorlogo.zone/logos/databricks/databricks-icon.svg"
curl -s -o "$ICONS_DIR/tableau.svg" "https://www.vectorlogo.zone/logos/tableau/tableau-icon.svg"

echo "Downloaded $(ls -1 $ICONS_DIR/*.svg 2>/dev/null | wc -l) icons to $ICONS_DIR"
